### PR TITLE
feat: integrate extended GraphQL scalars

### PR DESCRIPTION
**Pull request by BlasiusSecundus**

### CODE REVIEW

**Comment by setchy** [comment]
Nice!

fyi - there is an open PR to updated extended-scalars to use graphql-java:16.1
https://github.com/graphql-java/graphql-java-extended-scalars/pull/33

**Comment by setchy** [comment]
@BlasiusSecundus - 16.0.0 just got released - https://github.com/graphql-java/graphql-java-extended-scalars/releases/tag/16.0.0

**Comment by BlasiusSecundus** [comment]
Thanks @setchy, updated to 16.0.0.

**Comment by BlasiusSecundus** [comment]
That test failure, again, is related to the test subscription.

> Testing getRemainingResponses > Should properly return remaining responses after the Subscription was stopped. FAILED
>     java.lang.AssertionError: 
>     Expecting:
>       <[]>
>     to contain exactly (and in same order):
>       <[1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L]>
>     but could not find the following elements:
>       <[1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L]>
>         at com.graphql.spring.boot.test.GraphQLTestSubscriptionGetRemainingResponsesTest.shouldGetRemainingResponses(GraphQLTestSubscriptionGetRemainingResponsesTest.java:27)

**Pull request merged**
