### PR TITLE
GraphQL annotation support

### PR DESCRIPTION
**Pull request by BlasiusSecundus**
This PR adds support for the GraphQL Annotations library and an example project to demonstrate the usage of this feature - also demonstrating a viable workaround for the problem that GraphQL Annotations is not really dependency injection friendly. 

This feature is still work in progress (hence it is only a draft PR). However, it is ready for preliminary review as no fundamental changes are planned.

The following tasks are still on the to-do list: 
- improve the example project (not all features are demonstrated yet) - this also serves as an additional testing layer
- add documentation
- test, test and test...

### CODE REVIEW

**Comment by BlasiusSecundus** [comment]
No idea why Travis build failed. Log shows nothing...

**Comment by oliemansm** [comment]
Could you move the examples to the samples project? We want to move all samples to that separate project.

**Comment by BlasiusSecundus** [comment]
Sure, I'll move it there

**Comment by BlasiusSecundus** [comment]
Status update: I plan to finalize the MR in June, along with the sample project. I think it won't make it into the v7.1.0 release (which seems to be just around the corner).

**Comment by oliemansm** [comment]
Thanks a lot @BlasiusSecundus !

**Pull request merged**
