### PR TITLE
GraphiQL && Voyager with full CDNs dependencies fetching

### PR DESCRIPTION
**Pull request by Sparow199**
I'm waiting for your feedbacks. Thanks

### CODE REVIEW

**Comment by oliemansm** [comment]
Thanks for the contribution, @Sparow199!

**Comment by Sparow199** [comment]
Hello @oliemansm , could you launch a small release with this Pr ? i really need it in order to integrate it to my current projet. Thanks :)

**Comment by oliemansm** [comment]
I'm expecting another small PR actually because of an update in `graphql-java-servlet`. Once that's in I'll deploy a new release.

**Comment by Sparow199** [comment]
You have an idea about the release date ?

**Comment by oliemansm** [comment]
Releasing now, so should be available in Maven Central within hours

**Comment by imolorhe** [comment]
@Sparow199 Yeah you can easily add Altair in a similar way as well. Here's a simple implementation on JsFiddle: https://jsfiddle.net/imolorhe/zrjh2x08/

**Comment by Sparow199** [comment]
Nice, I'll work on it asap. Thanks you for example

**Pull request merged**
