### PR TITLE
feat: added ability to use strings for GraphQl queries when using GraphQLTestTemplate

### PR DESCRIPTION
**Pull request by bsara**
Currently, when using GraphQLTestTemplate, one can only submit queries that are in resource files. There are many clients, however, that may want to submit queries via a string that is inlined with their tests:

```java
gqlTestTemplate.post(
  "query blah {"
  + "  myField"
  + "}"
);
```

For these cases, I've added a series of overloaded `postForString` methods to `GraphQLTestTemplate` which allow the passing of a string value for a query instead of always requiring a Resource be used.

Simple usage is as follows:

```java
// Java
gqlTestTemplate.postForString(
  "query blah {"
  + "  myField"
  + "}"
);
```

```kotlin
// Kotlin
gqlTestTemplate.postForString("""
  query blah {
    myField
  }
""")
```

### CODE REVIEW

**Comment by m1ngyuan** [comment]
You can use 
`Mono<GraphQLResponse> post(GraphQLRequest request);`
Finish what you need

**Comment by bsara** [comment]
@m1ngyuan, that does not solve the same problem here. I'm looking to just pass a string as the query, not a `GraphQLRequest` object or a file resource. I don't really care about getting a reactive response back.

**Review by oliemansm — APPROVED** [review]

**Comment by oliemansm** [comment]
Thanks @bsara

**Comment by bsara** [comment]
Thanks for the merge @oliemansm

**Pull request merged**
