### PR TITLE
chore: upgrade to Spring Boot 2.5.2

### PR DESCRIPTION
**Pull request by BlasiusSecundus**
Like https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/636 but also passes commitlint.

### CODE REVIEW

**Comment by setchy** [comment]
@BlasiusSecundus - should we tweak the commitlint parameters to accept a character length slightly longer than 100, so that future springboot framework renovate updates don't also fail?

```
input: chore(deps): update dependency org.springframework.boot:org.springframework.boot.gradle.plugin to v2.4.6
✖   header must not be longer than 100 characters, current length is 104 [header-max-length]
```

Alternatively I can tweak the renovate shared settings to condense the commit subject for springboot framework updates

**Comment by BlasiusSecundus** [comment]
I think in this case it would be better to tweak renovate settings.

**Comment by setchy** [comment]
@BlasiusSecundus [renovate-config changed](https://github.com/graphql-java-kickstart/renovate-config/commit/b77891b1a20a7f0aace3f98248b2d234483f9c99) and tested on #636, so for next time it shouldn't need manual intervention.

For this instance, lets use #664

**Comment by setchy** [comment]
#674 auto updated to 2.5.3

**Pull request closed without merging**
