### PR TITLE
chore: build script improvements, Gradle upgrade to 6.2.2

### PR DESCRIPTION
**Pull request by BlasiusSecundus**
Notable improvements:
- upgrade Gradle Wrapper to version 6.2.1
- add the Official Gradle Wrapper Validation Action
(https://github.com/gradle/wrapper-validation-action)
- use Spring dependency management
- all dependency versions defined in gradle.properties
(excluding those only used in examples)
- update some dependency and plugin versions
- update deprecated `compile` / `runtime` dependency configurations
(replaced with `implementation` or `api` / `runtimeOnly`)
- remove deprecated `maven` plugin
- remove Lombok plugin (Lombok version is now managed by Spring)

Potential breaking changes:

- the `install` task no longer exists; use `publishToMavenLocal` instead
- Lombok-related tasks were removed

**Note**

This is quite a refactor and I hope that nothing is broken:) I have tested basic tasks like `check`, `publishToMavenLocal` etc. Also some tasks of the release plugin (e. g. `unSnapshot`, `updateVersion`).

I did not test (nor touched the configuration) of the Bintray plugin.

Please review / test it thoroughly to ensure that all necessary tasks still works as expected.

### CODE REVIEW

**Comment by oliemansm** [comment]
Thanks!

**Comment by oliemansm** [comment]
@BlasiusSecundus Could you resolve the merge conflicts so I can go ahead and merge it?

**Comment by BlasiusSecundus** [comment]
Conflicts resolved. 

However, I did could not make Voyager work, always got 404 (GraphiQL, Playground and Altair works file).

Also, I have not yet tested the reactive versions.

**Comment by oliemansm** [comment]
Thanks!

**Pull request merged**
