### PR TITLE
Fix @ExceptionHandler 

### PR DESCRIPTION
**Pull request by Sam-Kruglov**
related to https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/305 but it has become stale.
@oliemansm could you, please, take a look?

### CODE REVIEW

**Comment by Sam-Kruglov** [comment]
`GraphQLErrorHandlerTest` failed

**Comment by Sam-Kruglov** [comment]
Not sure if `getContext().publishEvent(new ApplicationReadyEvent(new SpringApplication(), new String[0], getContext()));` the best way but manually starting up spring context is also not the best way, so, at least it fits the rest of the code. 
Please, consider using [ApplicationContextRunner](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-test-autoconfig)

**Comment by Sam-Kruglov** [comment]
May I also propose that `GraphQLErrorHandlerFactory` does not deal with `DefaultGraphQLErrorHandler`? So that it is more flexible for the client to configure the default one

**Comment by Sam-Kruglov** [comment]
Another suggestion: make `GraphQLErrorFromExceptionHandler` and `GraphQLErrorFactory` public so that I can change the fallback values. E.g. I always want an error code in extensions, so I would change `GenericGraphQLError` and `ThrowableGraphQLError` at least

**Comment by oliemansm** [comment]
@Sam-Kruglov Just merged the other PR dealing with the same issue. Is there anything in this PR still relevant or has this now become obsolete?

**Comment by Sam-Kruglov** [comment]
Obsolete now. Thanks!

**Pull request closed without merging**
