### PR TITLE
Added Metrics Instrumentation (#137)

### PR DESCRIPTION
**Pull request by senzzzi**
@oliemansm I wrote some code for this Enhancement. I am not sure I used the right approach. I don't think it makes sense to have "MetricsInstrumentation" on graphql-java because it is specific for spring boot. Also, on "onCompleted", the throwable is always null even when I throw an exception when fetching data. Can you point out what I am doing wrong?

### CODE REVIEW

**Comment by oliemansm** [comment]
@senzzzi Haven't used micrometer before. Do you have a running example you can share? I see that a test is failing btw because it expects a `MeterRegistry`.

**Comment by senzzzi** [comment]
@oliemansm  I forgot to add a ConditionalOnBean annotation on the method that creates the MetricsInstrumentation Bean. 

To run this, the only thing needed is run some queries against the running instance and then call _/metrics/graphql.timer.operation_. The result should look like this:

screen shot 2018-10-10 at 10 58 08

**Comment by oliemansm** [comment]
@senzzzi If I simply add actuator starter to `example-graphql-tools` and set `graphql.servlet.actuator-metrics: true` I'm not getting that metric yet. Am I missing a step?

**Comment by senzzzi** [comment]
@oliemansm I updated the example inside the project. If you call a query to initialise the metric, you can then check it at `http://localhost:9000/actuator/metrics/graphql.timer.operation`. Tell me if you think it would be better to create a different example project only for metrics.

**Comment by senzzzi** [comment]
@oliemansm even with throwing a exception on the Query function I couldn't get the Throwable. I think it is because the errors are coming inside the executionResult but I need to investigate a little more. I don't fully know the code of how graphql resolves the data field.

**Comment by oliemansm** [comment]
@senzzzi Thanks for the example! I took a look at the fact that you couldn't catch any exceptions in `onCompleted` thrown while fetching data. That method appears to be called at the end of the entire parsing process. Exceptions translate into `errors` in the response, so those exceptions at this point are already handled and available within the `ExecutionResult`.

If you take a look at `TracingInstrumentation` in combination with `TracingSupport` you'll see they've overridden `beginParse(InstrumentationExecutionParameters)` to gather statistics. That's the place you want to override as well if you want to get a hold of any exceptions that were thrown during execution: 
```java
    @Override
    public InstrumentationContext<Document> beginParse(InstrumentationExecutionParameters parameters) {
        TracingSupport tracingSupport = parameters.getInstrumentationState();
        TracingSupport.TracingContext ctx = tracingSupport.beginParse();
        return whenCompleted((result, t) -> ctx.onEnd());
    }
```
https://github.com/graphql-java/graphql-java/blob/0e9b9e96083fece45fa5ee7bc500cddb13195b95/src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java#L56

You might want to consider re-using `TracingSupport` or taking a closer look at that class. Think it's a very nice example at the least for solving this. 

Which information do you want to expose to metrics? Is it just the main count and total time or is there anything else?

**Comment by senzzzi** [comment]
@oliemansm I made some changes and I am now using the `TracingInstrumentation` as my metrics source which makes total sense, there was no need to store the same data twice. I am also added another Instrumentation that allows to have timers on all operations without recording the time it takes to get all the fields. For me, I think it makes sense to have metrics for the time it takes to get all the data on a specific query but not for each field, it might be too expensive to have that enabled in production. Also, my code on MetricsInstrumentation is a bit "ugly", I would say. The TracingSupport class has all fields private with no getters so I had to look for a workaround on that.

**Comment by oliemansm** [comment]
@senzzzi I see what you mean. It makes it a bit volatile I'd say. The only way to solve that would be to make your own implementation/copy of `TracingInstrumentation` and `TracingSupport` to enable you to write clean code here?

**Comment by senzzzi** [comment]
Yes, that would solve, it would work as long as Instrumentation Interface and the ExecutionStrategy don't change. But I am not really a fan of duplicating code. On the other hand, I don't really like the parsing I have to make to get the metrics. I think we should probably go with what we have now but right better tests to assert that we don't break anything on a next bump of graphql-java. What do you think? I don't mind writing those..

**Pull request merged**
